GET http://localhost:3001/api/currency/

###
GET http://localhost:3001/api/currency/about

###
GET http://localhost:3001/api/currency/2
###
GET http://localhost:3001/api/currency/6


###
POST  http://localhost:3001/api/currency/ 
Content-Type: application/json

{
    "currencyCode": "SR",
    "countryId": 3,
    "conversionRate": 3.3
}

###
PUT http://localhost:3001/api/currency/4/0.53

###
DELETE http://localhost:3001/api/currency/23
###
DELETE http://localhost:3001/api/currency/9


###
GET http://localhost:3001/api/currency-country